name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          user: VictorAlexandreMuller
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          filename: github-metrics.svg
          plugin_isocalendar: no
          plugin_languages: no
          plugin_lines: yes
          plugin_traffic: yes
          plugin_stargazers: yes        # quantas estrelas seus projetos receberam
          plugin_contributors: yes      # pessoas que contribuíram em projetos seus
          plugin_followup: yes          # issues abertas / fechadas / evolução
          plugin_habits: yes            # horário do dia que você mais programa!
          plugin_achievements: yes 
          token: ${{ secrets.GITHUB_TOKEN }}
