name: GitHub Metrics

on:
  # Atualiza todo dia às 00:00 UTC
  schedule:
    - cron: "0 0 * * *"
  # Permite rodar manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          # <<< MUITO IMPORTANTE: seu usuário GitHub
          user: VictorAlexandreMuller
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo

          # Saída do arquivo
          filename: github-metrics.svg

          # Plugins que queremos
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8

          plugin_lines: yes

          plugin_traffic: yes

          # Token padrão do GitHub Actions (não precisa criar nada)
          token: ${{ secrets.GITHUB_TOKEN }}
